apiVersion: v2
appVersion: v0.9.0
description: An exporter for metrics in the InfluxDB format, transforms them and exposes them for consumption by Prometheus.
name: influxdb-exporter
version: 1.0.3
kubeVersion: ">=1.16.0-0"
keywords:
  - influxdb-exporter
home: https://github.com/Aste88/helm-charts/tree/master/charts/incubator/influxdb-exporter
icon: https://influxdata.github.io/branding/img/downloads/influxdata-logo--symbol--pool.jpg
sources:
  - https://github.com/prometheus/influxdb_exporter
maintainers:
  - name: Aste88
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add link to grafana Proxmox chart.
