apiVersion: v2
appVersion: v0.1.19
description: brave-sync helm package
name: brave-sync
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
- brave-sync
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/brave-sync
icon: https://brave-sync.org/icon
sources:
- https://github.com/brave-sync/brave-sync-docker
maintainers:
- name: brave-sync
  email: brave-sync@brave-sync.com
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
  - name: redis
    version: 16.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: dynamo-db
    version: 0.0.1
    repository: file://../dynamo-db/
    condition: dynamo-db.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
