name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  # cancel-in-progress: true

jobs:
  pr-metadata:
    uses: Aste88/helm-charts/actions/.github/workflows/pr-metadata.yaml@master

  pre-commit-check:
    uses: Aste88/helm-charts/actions/.github/workflows/pre-commit-check.yaml@master
    needs:
      - pr-metadata
    with:
      modifiedFiles: ${{ needs.pr-metadata.outputs.addedOrModifiedFiles }}

  charts-changelog:
    uses: Aste88/helm-charts/actions/.github/workflows/charts-changelog.yaml@master
    needs:
      - pr-metadata
      - pre-commit-check
    with:
      isRenovatePR: ${{ needs.pr-metadata.outputs.isRenovatePR }}
      modifiedCharts: ${{ needs.pr-metadata.outputs.addedOrModifiedCharts }}

  charts-lint:
    uses: Aste88/helm-charts/actions/.github/workflows/charts-lint.yaml@master
    needs:
      - pr-metadata
      - charts-changelog
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-metadata.outputs.addedOrModified }}

  charts-test:
    uses: Aste88/helm-charts/actions/.github/workflows/charts-test.yaml@master
    needs:
      - pr-metadata
      - charts-changelog
      - charts-lint
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-metadata.outputs.addedOrModified }}
